language: python
install:
  - pip install coveralls tox
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=docs
  - TOXENV=isort
  - TOXENV=manifest
script:
  - tox
after_success:
  - coveralls
sudo: false
notifications:
  slack:
    secure: GUabKu20PYIFkeBDmdr1/F5baTuXWJafjSWKub7fHAt9SWhw1AloN4J8cqr5j/AECrDrGjHZPafw6epc16Uxztrnn7gChhhxvZzot91boA68eYRWNMEyJu+TIVaxjkuG+qIBFa/wvCSYcIZYhFbvJGi+kzZu8dtzw0ulZVbAGMg=
